
package cz.rkr.movies.be.war.ws;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "TestWebServicePort", serviceName = "TestService", targetNamespace = "http://ws.war.be.movies.rkr.cz/", wsdlLocation = "file:/opt/rkr/svn/movies/trunk/be.war/src/main/resources/ws/wsdl/TestService.wsdl", endpointInterface = "cz.rkr.movies.be.war.ws.TestWebService")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class TestService_TestWebServicePortImpl
    implements TestWebService
{


    public TestService_TestWebServicePortImpl() {
    }

    /**
     * 
     */
    public void insertAccount() {
        //replace with your impl here
        return;
    }

}
